"""Top-level package for snowXSQL."""

__author__ = """Micah Johnson"""
__email__ = 'micah.johnson150@gmail.com'
__version__ = '0.1.0'



# Typical names we run into that need renaming
rename = {'location':'site_name',
         'top': 'depth',
         'height':'depth',
         'bottom':'bottom_depth',
         'site': 'site_id',
         'pitid': 'pit_id',
         'slope':'slope_angle',
         'weather':'weather_description',
         'sky': 'sky_cover',
         'notes':'site_notes',
         'sample_top_height':'depth',
         'deq':'equivalent_diameter',
         'operator':'surveyors',
         'observer':'surveyors',
         'total_snow_depth':'total_depth',
         'smp_serial_number':'instrument',
         'lat':'latitude',
         'long':'longitude',
         'lon':'longitude',
         'twt':'two_way_travel',
         'utmzone':'utm_zone',
         'measurement_tool':'instrument',
         'avgdensity':'density',
         'avg_density':'density',
         'dielectric_constant': 'permittivity',
         'airtc': 'air_temperature',
         'albedo': 'albedo',
         'bp': 'barometric_pressure',
         'cnr4tc': 'temperature',
         'id': 'imaginary_dielectric_permittivity',
         'irsensor_xxx': 'sensor_body_temperature',
         'irtarget_xxx': 'infrared_surface_temperature',
         'ldn': 'downward_looking_longwave_radiation',
         'ldnco': 'downward_looking_longwave_radiation',
         'lup': 'upward_looking_longwave_radiation',
         'lupco': 'upward_looking_longwave_radiation',
         'rd': 'real_dielectric_permittivity',
         'rh': 'relative_humidity',
         'rlnet': 'net_longwave_radiation',
         'rn': 'total_net_radiation',
         'rsnet': 'net_shortwave_radiation',
         'sc': 'soil_conductivity',
         'sct': 'soil_conductivity',
         'sdn': 'downward_looking_shortwave_radiation',
         'sm': 'soil_moisture',
         'snow depth': 'mean_snow_depth',
         'sup': 'upward_looking_shortwave_radiation',
         'tc': 'soil_temperature',
         'tcstringc-sxx': 'soil_temperature',
         'tcstringc-xx': 'air_snow_temperature',
         'winddir': 'wind_direction',
         'winddir_10ft_d1_wvt': 'unit_vector_mean_wind_direction',
         'wsms': 'mean_horizontal_wind_speed'
         }

# Typical Units we run into
units = {
  'depth':'cm',
  'two_way_travel':'ns',
  'swe':'mm',
  'density':'kg/m^3',
  # Met station units
  'air_snow_temperature': 'c',
  'air_temperature': 'c',
  'albedo': 'none',
  'barometric_pressure': 'kpa',
  'downward_looking_longwave_radiation': 'w/m^2',
  'downward_looking_shortwave_radiation': 'w/m^2',
  'imaginary_dielectric_permittivity': 'none',
  'infrared_surface_temperature': 'c',
  'infrared_surface_temperature_0cm_above_soil': 'c',
  'infrared_surface_temperature_100cm_above_soil': 'c',
  'infrared_surface_temperature_10cm_above_soil': 'c',
  'infrared_surface_temperature_125cm_above_soil': 'c',
  'infrared_surface_temperature_150cm_above_soil': 'c',
  'infrared_surface_temperature_175cm_above_soil': 'c',
  'infrared_surface_temperature_200cm_above_soil': 'c',
  'infrared_surface_temperature_20cm_above_soil': 'c',
  'infrared_surface_temperature_225cm_above_soil': 'c',
  'infrared_surface_temperature_250cm_above_soil': 'c',
  'infrared_surface_temperature_275cm_above_soil': 'c',
  'infrared_surface_temperature_2cm_above_soil': 'c',
  'infrared_surface_temperature_300cm_above_soil': 'c',
  'infrared_surface_temperature_30_degrees_north': 'c',
  'infrared_surface_temperature_30_degrees_south': 'c',
  'infrared_surface_temperature_30cm_above_soil': 'c',
  'infrared_surface_temperature_40cm_above_soil': 'c',
  'infrared_surface_temperature_50cm_above_soil': 'c',
  'infrared_surface_temperature_5cm_above_soil': 'c',
  'infrared_surface_temperature_75cm_above_soil': 'c',
  'infrared_surface_temperature_nadir1': 'c',
  'infrared_surface_temperature_nadir2': 'c',
  'infrared_surface_temperature_s10cm_above_soil': 'c',
  'infrared_surface_temperature_s20cm_above_soil': 'c',
  'infrared_surface_temperature_s2cm_above_soil': 'c',
  'infrared_surface_temperature_s30cm_above_soil': 'c',
  'infrared_surface_temperature_s40cm_above_soil': 'c',
  'infrared_surface_temperature_s50cm_above_soil': 'c',
  'infrared_surface_temperature_s5cm_above_soil': 'c',
  'mean_horizontal_wind_speed': 'm/s',
  'mean_snow_depth': 'm',
  'net_longwave_radiation': 'w/m^2',
  'net_shortwave_radiation': 'w/m^2',
  'real_dielectric_permittivity': 'none',
  'relative_humidity': '%',
  'sensor_body_temperature': 'c',
  'soil_conductivity': 's/m',
  'soil_moisture': 'water fraction by volume',
  'soil_temperature': 'c',
  'temperature': 'c',
  'total_net_radiation': 'w/m^2',
  'unit_vector_mean_wind_direction': 'degrees from north',
  'upward_looking_longwave_radiation': 'w/m^2',
  'upward_looking_shortwave_radiation': 'w/m^2',
  'wind_direction': 'deg'}
