"""Top-level package for snowXSQL."""

__author__ = """Micah Johnson"""
__email__ = 'micah.johnson150@gmail.com'
__version__ = '0.1.0'



# Typical names we run into that need renaming
rename = {'location':'site_name',
         'top': 'depth',
         'height':'depth',
         'bottom':'bottom_depth',
         'site': 'site_id',
         'pitid': 'pit_id',
         'slope':'slope_angle',
         'weather':'weather_description',
         'sky': 'sky_cover',
         'notes':'site_notes',
         'sample_top_height':'depth',
         'deq':'equivalent_diameter',
         'operator':'surveyors',
         'observer':'surveyors',
         'total_snow_depth':'total_depth',
         'smp_serial_number':'instrument',
         'lat':'latitude',
         'long':'longitude',
         'lon':'longitude',
         'twt':'two_way_travel',
         'measurement_tool':'instrument',
         'avgdensity':'density',
         'avg_density':'density',
         'dielectric_constant': 'permittivity',
         'AirTC': 'air_temperature',
         'Albedo': 'albedo',
         'BP': 'barometric_pressure',
         'CNR4TC': 'temperature',
         'ID': 'imaginary_dielectric_permittivity',
         'IRsensor_XXX': 'sensor_body_temperature',
         'IRtarget_30degN_C_Avg': 'infrared_surface_temperature_30_degrees_north',
         'IRtarget_30degS_C_Avg': 'infrared_surface_temperature_30_degrees_south',
         'IRtarget_XXX': 'infrared_surface_temperature',
         'IRtarget_nadir1_C_Avg': 'infrared_surface_temperature_nadir1',
         'IRtarget_nadir2_C_Avg': 'infrared_surface_temperature_nadir2',
         'LDnCo': 'downward_looking_longwave_radiation',
         'LUpCo': 'upward_looking_longwave_radiation',
         'Ldn': 'downward_looking_longwave_radiation',
         'Lup': 'upward_looking_longwave_radiation',
         'RD': 'real_dielectric_permittivity',
         'RH': 'relative_humidity',
         'RlNet': 'net_longwave_radiation',
         'Rn': 'total_net_radiation',
         'RsNet': 'net_shortwave_radiation',
         'SC': 'soil_conductivity',
         'SCt': 'soil_conductivity',
         'SDn': 'downward_looking_shortwave_radiation',
         'SM': 'soil_moisture',
         'Snow Depth': 'mean_snow_depth',
         'Sup': 'upward_looking_shortwave_radiation',
         'TC': 'soil_temperature',
         'TCstringC_0cm_Avg': 'infrared_surface_temperature_0cm_above_soil',
         'TCstringC_100cm_Avg': 'infrared_surface_temperature_100cm_above_soil',
         'TCstringC_10cm_Avg': 'infrared_surface_temperature_10cm_above_soil',
         'TCstringC_125cm_Avg': 'infrared_surface_temperature_125cm_above_soil',
         'TCstringC_150cm_Avg': 'infrared_surface_temperature_150cm_above_soil',
         'TCstringC_175cm_Avg': 'infrared_surface_temperature_175cm_above_soil',
         'TCstringC_200cm_Avg': 'infrared_surface_temperature_200cm_above_soil',
         'TCstringC_20cm_Avg': 'infrared_surface_temperature_20cm_above_soil',
         'TCstringC_225cm_Avg': 'infrared_surface_temperature_225cm_above_soil',
         'TCstringC_250cm_Avg': 'infrared_surface_temperature_250cm_above_soil',
         'TCstringC_275cm_Avg': 'infrared_surface_temperature_275cm_above_soil',
         'TCstringC_2cm_Avg': 'infrared_surface_temperature_2cm_above_soil',
         'TCstringC_300cm_Avg': 'infrared_surface_temperature_300cm_above_soil',
         'TCstringC_30cm_Avg': 'infrared_surface_temperature_30cm_above_soil',
         'TCstringC_40cm_Avg': 'infrared_surface_temperature_40cm_above_soil',
         'TCstringC_50cm_Avg': 'infrared_surface_temperature_50cm_above_soil',
         'TCstringC_5cm_Avg': 'infrared_surface_temperature_5cm_above_soil',
         'TCstringC_75cm_Avg': 'infrared_surface_temperature_75cm_above_soil',
         'TCstringC_s10cm_Avg': 'infrared_surface_temperature_s10cm_above_soil',
         'TCstringC_s20cm_Avg': 'infrared_surface_temperature_s20cm_above_soil',
         'TCstringC_s2cm_Avg': 'infrared_surface_temperature_s2cm_above_soil',
         'TCstringC_s30cm_Avg': 'infrared_surface_temperature_s30cm_above_soil',
         'TCstringC_s40cm_Avg': 'infrared_surface_temperature_s40cm_above_soil',
         'TCstringC_s50cm_Avg': 'infrared_surface_temperature_s50cm_above_soil',
         'TCstringC_s5cm_Avg': 'infrared_surface_temperature_s5cm_above_soil',
         'WSms': 'mean_horizontal_wind_speed',
         'WindDir': 'wind_direction',
         'WindDir_10ft_D1_WVT': 'unit_vector_mean_wind_direction'
         }

# Typical Units we run into
units = {
  'depth':'cm',
  'two_way_travel':'ns',
  'swe':'mm',
  'density':'kg/m^3',
  # Met station units
  'air_snow_temperature': 'c',
  'air_temperature': 'c',
  'albedo': 'none',
  'barometric_pressure': 'kpa',
  'downward_looking_longwave_radiation': 'w/m^2',
  'downward_looking_shortwave_radiation': 'w/m^2',
  'imaginary_dielectric_permittivity': 'none',
  'infrared_surface_temperature': 'c',
  'infrared_surface_temperature_0cm_above_soil': 'c',
  'infrared_surface_temperature_100cm_above_soil': 'c',
  'infrared_surface_temperature_10cm_above_soil': 'c',
  'infrared_surface_temperature_125cm_above_soil': 'c',
  'infrared_surface_temperature_150cm_above_soil': 'c',
  'infrared_surface_temperature_175cm_above_soil': 'c',
  'infrared_surface_temperature_200cm_above_soil': 'c',
  'infrared_surface_temperature_20cm_above_soil': 'c',
  'infrared_surface_temperature_225cm_above_soil': 'c',
  'infrared_surface_temperature_250cm_above_soil': 'c',
  'infrared_surface_temperature_275cm_above_soil': 'c',
  'infrared_surface_temperature_2cm_above_soil': 'c',
  'infrared_surface_temperature_300cm_above_soil': 'c',
  'infrared_surface_temperature_30_degrees_north': 'c',
  'infrared_surface_temperature_30_degrees_south': 'c',
  'infrared_surface_temperature_30cm_above_soil': 'c',
  'infrared_surface_temperature_40cm_above_soil': 'c',
  'infrared_surface_temperature_50cm_above_soil': 'c',
  'infrared_surface_temperature_5cm_above_soil': 'c',
  'infrared_surface_temperature_75cm_above_soil': 'c',
  'infrared_surface_temperature_nadir1': 'c',
  'infrared_surface_temperature_nadir2': 'c',
  'infrared_surface_temperature_s10cm_above_soil': 'c',
  'infrared_surface_temperature_s20cm_above_soil': 'c',
  'infrared_surface_temperature_s2cm_above_soil': 'c',
  'infrared_surface_temperature_s30cm_above_soil': 'c',
  'infrared_surface_temperature_s40cm_above_soil': 'c',
  'infrared_surface_temperature_s50cm_above_soil': 'c',
  'infrared_surface_temperature_s5cm_above_soil': 'c',
  'mean_horizontal_wind_speed': 'm/s',
  'mean_snow_depth': 'm',
  'net_longwave_radiation': 'w/m^2',
  'net_shortwave_radiation': 'w/m^2',
  'real_dielectric_permittivity': 'none',
  'relative_humidity': '%',
  'sensor_body_temperature': 'c',
  'soil_conductivity': 's/m',
  'soil_moisture': 'water fraction by volume',
  'soil_temperature': 'c',
  'temperature': 'c',
  'total_net_radiation': 'w/m^2',
  'unit_vector_mean_wind_direction': 'degrees from north',
  'upward_looking_longwave_radiation': 'w/m^2',
  'upward_looking_shortwave_radiation': 'w/m^2',
  'wind_direction': 'deg'}
