"""Top-level package for snowXSQL."""

__author__ = """Micah Johnson"""
__email__ = 'micah.johnson150@gmail.com'
__version__ = '0.1.0'


# Typical names we run into that need renaming
rename = {'location':'site_name',
         'top': 'depth',
         'height':'depth',
         'bottom':'bottom_depth',
         'site': 'site_id',
         'pitid': 'pit_id',
         'slope':'slope_angle',
         'weather':'weather_description',
         'sky': 'sky_cover',
         'notes':'site_notes',
         'sample_top_height':'depth',
         'deq':'equivalent_diameter',
         'operator':'surveyors',
         'observer':'surveyors',
         'total_snow_depth':'total_depth',
         'smp_serial_number':'instrument',
         'lat':'latitude',
         'long':'longitude',
         'lon':'longitude',
         'twt':'two_way_travel',
         'utmzone':'utm_zone',
         'measurement_tool':'instrument',
         'avgdensity':'density',
         'avg_density':'density',
         'dielectric_constant': 'permittivity',
         # MET names
         'airtc_20ft_avg': 'air_temperature_20ft_above_ground',
         'irtarget_30degn_c_avg': 'infrared_surface_temperature',
         'irtarget_30degs_c_avg': 'infrared_surface_temperature',
         'irtarget_nadir1_c_avg': 'infrared_surface_temperature',
         'irtarget_nadir2_c_avg': 'infrared_surface_temperature',
         'ldnco_avg': 'downward_looking_longwave_radiation',
         'lupco_avg': 'upward_looking_longwave_radiation',
         'rh_10ft': 'relative_humidity_10ft_above_ground',
         'rh_20ft': 'relative_humidity_20ft_above_ground',
         'sdn_avg': 'downward_looking_shortwave_radiation',
         'sm_20cm_avg': 'soil_moisture_20cm_below_ground',
         'sm_50cm_avg': 'soil_moisture_50cm_below_ground',
         'sm_5cm_avg': 'soil_moisture_5cm_below_ground',
         'snow depth': 'mean_snow_depth',
         'sup_avg': 'upward_looking_shortwave_radiation',
         'tc_20cm_avg': 'soil_temperature_20cm_below_ground',
         'tc_50cm_avg': 'soil_temperature_50cm_below_ground',
         'tc_5cm_avg': 'soil_temperature_5cm_below_ground',
         'tcstringc_0cm_avg': 'air_snow_temperature_0cm_below_ground',
         'tcstringc_100cm_avg': 'air_snow_temperature_100cm_below_ground',
         'tcstringc_10cm_avg': 'air_snow_temperature_10cm_below_ground',
         'tcstringc_125cm_avg': 'air_snow_temperature_125cm_below_ground',
         'tcstringc_150cm_avg': 'air_snow_temperature_150cm_below_ground',
         'tcstringc_175cm_avg': 'air_snow_temperature_175cm_below_ground',
         'tcstringc_200cm_avg': 'air_snow_temperature_200cm_below_ground',
         'tcstringc_20cm_avg': 'air_snow_temperature_20cm_below_ground',
         'tcstringc_225cm_avg': 'air_snow_temperature_225cm_below_ground',
         'tcstringc_250cm_avg': 'air_snow_temperature_250cm_below_ground',
         'tcstringc_275cm_avg': 'air_snow_temperature_275cm_below_ground',
         'tcstringc_2cm_avg': 'air_snow_temperature_2cm_below_ground',
         'tcstringc_300cm_avg': 'air_snow_temperature_300cm_below_ground',
         'tcstringc_30cm_avg': 'air_snow_temperature_30cm_below_ground',
         'tcstringc_40cm_avg': 'air_snow_temperature_40cm_below_ground',
         'tcstringc_50cm_avg': 'air_snow_temperature_50cm_below_ground',
         'tcstringc_5cm_avg': 'air_snow_temperature_5cm_below_ground',
         'tcstringc_75cm_avg': 'air_snow_temperature_75cm_below_ground',
         'tcstringc_s10cm_avg': 'soil_temperature_s10cm_below_ground',
         'tcstringc_s20cm_avg': 'soil_temperature_s20cm_below_ground',
         'tcstringc_s2cm_avg': 'soil_temperature_s2cm_below_ground',
         'tcstringc_s30cm_avg': 'soil_temperature_s30cm_below_ground',
         'tcstringc_s40cm_avg': 'soil_temperature_s40cm_below_ground',
         'tcstringc_s50cm_avg': 'soil_temperature_s50cm_below_ground',
         'tcstringc_s5cm_avg': 'soil_temperature_s5cm_below_ground',
         'winddir_10ft': 'wind_direction_10ft_above_ground',
         'winddir_20ft': 'wind_direction_20ft_above_ground',
         'wsms_10ft_avg': 'mean_horizontal_wind_speed_10ft_above_ground',
         'wsms_20ft_avg': 'mean_horizontal_wind_speed_20ft_above_ground'
         }


# Typical Units we run into
units = {
  'depth':'cm',
  'two_way_travel':'ns',
  'swe':'mm',
  'density':'kg/m^3',
  'air_snow_temperature_0cm_below_ground': 'c',
  'air_snow_temperature_100cm_below_ground': 'c',
  'air_snow_temperature_10cm_below_ground': 'c',
  'air_snow_temperature_125cm_below_ground': 'c',
  'air_snow_temperature_150cm_below_ground': 'c',
  'air_snow_temperature_175cm_below_ground': 'c',
  'air_snow_temperature_200cm_below_ground': 'c',
  'air_snow_temperature_20cm_below_ground': 'c',
  'air_snow_temperature_225cm_below_ground': 'c',
  'air_snow_temperature_250cm_below_ground': 'c',
  'air_snow_temperature_275cm_below_ground': 'c',
  'air_snow_temperature_2cm_below_ground': 'c',
  'air_snow_temperature_300cm_below_ground': 'c',
  'air_snow_temperature_30cm_below_ground': 'c',
  'air_snow_temperature_40cm_below_ground': 'c',
  'air_snow_temperature_50cm_below_ground': 'c',
  'air_snow_temperature_5cm_below_ground': 'c',
  'air_snow_temperature_75cm_below_ground': 'c',
  'air_temperature_10ft_above_ground': 'c',
  'air_temperature_20ft_above_ground': 'c',
  'downward_looking_longwave_radiation': 'w/m^2',
  'downward_looking_shortwave_radiation': 'w/m^2',
  'infrared_surface_temperature_30_degrees_north': 'c',
  'infrared_surface_temperature_30_degrees_south': 'c',
  'infrared_surface_temperature_nadir1': 'c',
  'infrared_surface_temperature_nadir2': 'c',
  'mean_horizontal_wind_speed_10ft_above_ground': 'm/s',
  'mean_horizontal_wind_speed_20ft_above_ground': 'm/s',
  'mean_snow_depth': 'm',
  'relative_humidity_10ft_above_ground': '%',
  'relative_humidity_20ft_above_ground': '%',
  'soil_moisture_20cm_below_ground': 'water fraction by volume',
  'soil_moisture_50cm_below_ground': 'water fraction by volume',
  'soil_moisture_5cm_below_ground': 'water fraction by volume',
  'soil_temperature_20cm_below_ground': 'c',
  'soil_temperature_50cm_below_ground': 'c',
  'soil_temperature_5cm_below_ground': 'c',
  'soil_temperature_s10cm_below_ground': 'c',
  'soil_temperature_s20cm_below_ground': 'c',
  'soil_temperature_s2cm_below_ground': 'c',
  'soil_temperature_s30cm_below_ground': 'c',
  'soil_temperature_s40cm_below_ground': 'c',
  'soil_temperature_s50cm_below_ground': 'c',
  'soil_temperature_s5cm_below_ground': 'c',
  'upward_looking_longwave_radiation': 'w/m^2',
  'upward_looking_shortwave_radiation': 'w/m^2',
  'wind_direction_10ft_above_ground': 'deg',
  'wind_direction_20ft_above_ground': 'deg'
}

# Known possible types of profiles and points not in here will throw an error
available_data_names = ['density', 'permittivity','lwc_vol', 'temperature',
                'force', 'reflectance','sample_signal',
                'specific_surface_area', 'equivalent_diameter',
                'grain_size', 'hand_hardness', 'grain_type',
                'manual_wetness', 'two_way_travel', 'snow_depth','swe',
                 # Met station data_names names
                'air_temperature_10ft_above_ground',
                'relative_humidity_10ft_above_ground',
                'air_temperature_20ft_above_ground',
                'relative_humidity_20ft_above_ground',
                'mean_horizontal_wind_speed_10ft_above_ground',
                'wind_direction_10ft_above_ground',
                'mean_horizontal_wind_speed_20ft_above_ground',
                'wind_direction_20ft_above_ground',
                'upward_looking_shortwave_radiation',
                'downward_looking_shortwave_radiation',
                'upward_looking_longwave_radiation',
                'downward_looking_longwave_radiation',
                'infrared_surface_temperature_nadir1',
                'infrared_surface_temperature_nadir2',
                'infrared_surface_temperature_30_degrees_north',
                'infrared_surface_temperature_30_degrees_south',
                'soil_temperature_s50cm_below_ground',
                'soil_temperature_s40cm_below_ground',
                'soil_temperature_s30cm_below_ground',
                'soil_temperature_s20cm_below_ground',
                'soil_temperature_s10cm_below_ground',
                'soil_temperature_s5cm_below_ground',
                'soil_temperature_s2cm_below_ground',
                'air_snow_temperature_0cm_below_ground',
                'air_snow_temperature_2cm_below_ground',
                'air_snow_temperature_5cm_below_ground',
                'air_snow_temperature_10cm_below_ground',
                'air_snow_temperature_20cm_below_ground',
                'air_snow_temperature_30cm_below_ground',
                'air_snow_temperature_40cm_below_ground',
                'air_snow_temperature_50cm_below_ground',
                'air_snow_temperature_75cm_below_ground',
                'air_snow_temperature_100cm_below_ground',
                'air_snow_temperature_125cm_below_ground',
                'air_snow_temperature_150cm_below_ground',
                'air_snow_temperature_175cm_below_ground',
                'air_snow_temperature_200cm_below_ground',
                'air_snow_temperature_225cm_below_ground',
                'air_snow_temperature_250cm_below_ground',
                'air_snow_temperature_275cm_below_ground',
                'air_snow_temperature_300cm_below_ground',
                'soil_moisture_5cm_below_ground',
                'soil_temperature_5cm_below_ground',
                'soil_moisture_20cm_below_ground',
                'soil_temperature_20cm_below_ground',
                'soil_moisture_50cm_below_ground',
                'soil_temperature_50cm_below_ground',
                'mean_snow_depth',
                ]
