
name: Pytest

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install flake8
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # use flake8 to check formatting, based on example here https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html
          flake8 . --count --select=C,E,F,W,B,B950 --max-complexity=10 --max-line-length=88 --statistics --extend-ignore=E203
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, '3.10']

    services:

      postgis:
        image: kartoza/postgis:14-3.2
        env:
          POSTGRES_PASSWORD: db_builder
          POSTGRES_USER: builder
          POSTGRES_DB: test
          TZ: 'UTC'
          PGTZ: 'UTC'
          POSTGIS_GDAL_ENABLED_DRIVERS: 'ENABLE_ALL'
          POSTGIS_ENABLE_OUTDB_RASTERS: 'True'
        ports:
          - 5432:5432
        volumes:
          - /home/runner/work/:/home/runner/work/

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y postgis gdal-bin
          python3 -m pip install --upgrade pip
          python3 -m pip install -e ".[dev]"
      - name: Test with pytest
        run: |
          pytest -s
